# Generated by Django 4.0.3 on 2022-04-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dateorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('DateOfBirthday', models.DateField()),
            ],
        ),
    ]
