# Generated by Django 4.0.3 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0004_salesorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
